name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Print Go version
      run: go version

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Run tests
      run: |
        echo "Running tests..."
        go test -v ./... || echo "No tests found"

    - name: Build application
      run: |
        echo "Building application..."
        go build -v -o anime-service ./cmd/api/main.go
        ls -l anime-service

    - name: Debug SSH Connection
      run: |
        echo "Checking SSH connection details"
        echo "Host: ${{ secrets.SSH_HOST }}"
        echo "Port: ${{ secrets.SSH_PORT }}"
        echo "User: ${{ secrets.SSH_USER }}"

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: "${{ secrets.SSH_HOST }}"
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "Starting deployment process..."
          mkdir -p /opt/anime-service
          echo "Directory created"
          rm -f /opt/anime-service/anime-service
          echo "Old binary removed"

    - name: Copy Binary
      uses: appleboy/scp-action@master
      with:
        host: "${{ secrets.SSH_HOST }}"
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: anime-service
        target: /opt/anime-service/
        debug: true

    - name: Setup and Start Service
      uses: appleboy/ssh-action@master
      with:
        host: "${{ secrets.SSH_HOST }}"
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "Setting up service..."
          chmod +x /opt/anime-service/anime-service
          echo "Binary made executable"

          cat > /etc/systemd/system/anime-service.service << EOL
          [Unit]
          Description=Anime Service
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/opt/anime-service
          ExecStart=/opt/anime-service/anime-service
          Restart=on-failure
          User=root

          [Install]
          WantedBy=multi-user.target
          EOL

          echo "Systemd service file created"
          systemctl daemon-reload
          systemctl enable anime-service
          systemctl restart anime-service
          systemctl status anime-service