name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Resolve IPv6 to IP
      run: |
        # Получаем IPv4 адрес
        IPV4=$(dig +short ${{ secrets.SSH_HOST }})
        echo "Resolved IP: $IPV4"
        echo "RESOLVED_IP=$IPV4" >> $GITHUB_ENV

    - name: Build application
      run: go build -v -o anime-service ./cmd/api/main.go

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: "${{ env.RESOLVED_IP }}"
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          mkdir -p /opt/anime-service
          rm -f /opt/anime-service/anime-service

    - name: Copy Binary
      uses: appleboy/scp-action@master
      with:
        host: "${{ env.RESOLVED_IP }}"
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: anime-service
        target: /opt/anime-service/

    - name: Setup Service
      uses: appleboy/ssh-action@master
      with:
        host: "${{ env.RESOLVED_IP }}"
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          chmod +x /opt/anime-service/anime-service

          cat > /etc/systemd/system/anime-service.service << EOL
          [Unit]
          Description=Anime Service
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/opt/anime-service
          ExecStart=/opt/anime-service/anime-service
          Restart=on-failure
          User=root

          [Install]
          WantedBy=multi-user.target
          EOL

          systemctl daemon-reload
          systemctl enable anime-service
          systemctl restart anime-service