name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Создаем директорию для проекта
          mkdir -p /opt/anime-service

          # Клонируем репозиторий
          cd /opt/anime-service
          git clone https://github.com/merdernoty/anime-service.git .
          
          # Устанавливаем Go если нужно
          wget https://go.dev/dl/go1.24.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.24.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

          # Собираем проект
          go mod download
          go build -v -o anime-service ./cmd/api/main.go

          # Создаем systemd service
          cat > /etc/systemd/system/anime-service.service << EOL
          [Unit]
          Description=Anime Service
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory=/opt/anime-service
          ExecStart=/opt/anime-service/anime-service
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
          EOL

          # Перезагружаем systemd и стартуем сервис
          systemctl daemon-reload
          systemctl enable anime-service
          systemctl restart anime-service